name: sweatter_client
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  # state manager
  flutter_riverpod: ^3.2.0
  # navigation
  go_router: ^17.0.1
  # data
  dio: ^5.9.0
  drift: ^2.30.1
  shared_preferences: ^2.5.4
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  # ui
  google_fonts: ^8.0.0
  lucide_icons_flutter: ^3.1.9
  flutter_native_splash: ^2.4.7
  window_manager: ^0.5.1
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  # app icons
  icons_launcher: ^3.0.3
  # lints
  riverpod_lint: ^3.0.0-dev.4
  flutter_lints: ^6.0.0
  custom_lint: ^0.5.11

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700





