name: sweatter_server
description: Сервер для мессенджера Sweatter
version: 1.0.0


environment:
  sdk: ^3.10.4

dependencies:
  #server
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_web_socket: ^3.0.0
  #di
  get_it: ^9.2.0
  #data
  drift: ^2.31.0
  sqlite3: ^2.9.4
  bcrypt: ^1.2.0
  

dev_dependencies:
  drift_dev: ^2.31.0
  build_runner: ^2.11.0
  lints: ^6.1.0

